name: Daily R Script Execution

on:
  push:
    branches:
      - main  # Change this to the main branch name

jobs:
  import-data:
    runs-on: ubuntu-latest

    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
 
      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::glue
            any::purrr
            any::tibble
            any::ralger
            any::readr
            any::ralger

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Execute R script
        run: Rscript -e 'source("premarket.R")'  
        
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add market-watch.csv
          git commit -m 'Data updated' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
